# -*- mode: ruby -*-
# vi: set ft=ruby :

# Match platform-apps at
# /resources/deployer/terraform/tfmodules/onprem/ami.tf
# and /resources/deployer/config/ami.yaml
#
# Options at: https://portal.cloud.hashicorp.com/vagrant/discover
VAGRANT_BOXES = {
  ubuntu_jammy: {
    box: "ubuntu/jammy64",
    box_version: "20241002.0.0"
  },
  ubuntu_focal: {
    box: "ubuntu/focal64",
    box_version: "20240821.0.1"
  },
  rhel: {
    box: "generic/rhel9",
    box_version: "4.3.12",
  }
}

count  = (ENV["NODE_COUNT"] || 1).to_i
fail("NODE_COUNT must be a positive integer") if count < 1

distro = (ENV["NODE_DISTRO"] || "ubuntu_jammy").to_sym
fail("NODE_DISTRO '#{distro}' is not supported") unless VAGRANT_BOXES.key?(distro)

node_info = VAGRANT_BOXES[distro]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]

  config.vm.provision :file, source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.box_check_update = false

  (0...count).each do |i|
    config.vm.define "node-#{i}" do |c|
      c.vm.box         = node_info[:box]
      c.vm.box_version = node_info[:box_version]

      c.vm.network :private_network, ip: "192.168.50.1#{i}"

      # Should reflect requirements of the bundle chosen in
      # run.sh (chosen from `aws lightsail get-bundles`)
      c.vm.provider :virtualbox do |vb|
        vb.cpus = 2
        vb.memory = "4096"

        # NOTE: VirtualBox v6.x is SLOW with the following setting
        # vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end
end
