# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOXES = {
  ubuntu_bionic: {
    box: "ubuntu/bionic64",
    box_version: "20190513.0.0"
  },
  ubuntu_xenial: {
    box: "ubuntu/xenial64",
    box_version: "20190308.0.0"
  },
  centos: {
    box: "centos/7",
    box_version: "1902.01",
  },
  rhel: {
    box: "generic/rhel7",
    box_version: "1.9.10",
  }
}

count  = (ENV["NODE_COUNT"] || 1).to_i
fail("NODE_COUNT must be a positive integer") if count < 1

distro = (ENV["NODE_DISTRO"] || "ubuntu_xenial").to_sym
fail("NODE_DISTRO '#{distro}' is not supported") unless VAGRANT_BOXES.key?(distro)

node_info = VAGRANT_BOXES[distro]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]

  config.vm.provision :file, source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.box_check_update = false

  (0...count).each do |i|
    config.vm.define "node-#{i}" do |c|
      c.vm.box         = node_info[:box]
      c.vm.box_version = node_info[:box_version]

      c.vm.network :private_network, ip: "192.168.50.1#{i}"

      c.vm.provider :virtualbox do |vb|
        vb.cpus = 2
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
    end
  end
end
