---
- name: Fetch Helm Version
  command: helm version --server
  changed_when: false
  register: helm_version
  ignore_errors: yes
  run_once: true

- name: Create K8s Service Account
  command: kubectl -n kube-system create serviceaccount tiller
  when: helm_version is failed
  run_once: true

- name: Create Cluster Role Binding
  command: kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  when: helm_version is failed
  run_once: true

- name: helm Init tiller
  command: helm init --service-account tiller --wait
  when: helm_version is failed
  run_once: true

# # Create Secrets
- name: Probe tls-ca Secret
  command: kubectl --namespace cattle-system get secrets tls-ca
  register: secret
  changed_when: false
  ignore_errors: true
  run_once: true

- name: Create tls-ca Secret
  become: yes
  command: kubectl --namespace cattle-system create secret generic tls-ca --from-file=cacerts.pem=/etc/ssl/private/dominodatalab.com.pem
  when: secret is failed 
  run_once: true

# # Install Rancher
- name: Probe Helm Repos
  command: helm repo list
  register: repos
  run_once: true
  changed_when: false

- name: Add Rancher Repo
  command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  run_once: true
  when: "'rancher-stable' not in repos.stdout"

- name: Probe cert-manager Custom Resource Definition
  command: kubectl get CustomResourceDefinition certificates.certmanager.k8s.io
  run_once: true
  ignore_errors: true
  changed_when: false
  register: crd

- name: Install Custom Resource Definition
  command: kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
  run_once: true
  when: crd is failed

- name: Probe cert-manager Namespace
  command: kubectl get ns cert-manager
  changed_when: false
  ignore_errors: yes
  run_once: yes
  register: certmanager_ns

- name: Create cert-manager Namespace
  command: kubectl create namespace cert-manager
  run_once: true
  when: certmanager_ns is failed

- name: Probe cert-manager Namespace Label
  command: kubectl get namespace --selector certmanager.k8s.io/disable-validation=true
  changed_when: false
  run_once: true
  register: certmanager_ns_label

- name: Disable Resource Validation on cert-manager Namespace
  command: kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
  run_once: true
  when: "'No resources found' in certmanager_ns_label.stderr"

- name: Add Jetstack Repo for cert-manager
  command: helm repo add jetstack https://charts.jetstack.io
  when: "'jetstack' not in repos.stdout"
  run_once: true
  register: jetstack_repo

- name: Update Helm Repo
  command: helm repo update
  when: jetstack_repo is changed
  run_once: true

- name: Probe cert-manager chart
  command: helm list
  changed_when: false
  run_once: true
  register: charts

- name: Install cert-manager
  command: helm install --name cert-manager --namespace cert-manager --version v0.9.1 jetstack/cert-manager --description='RanchHand Deploy' --wait
  run_once: true
  when: "'cert-manager' not in charts.stdout"

- name: Install Rancher
  command: helm install rancher-stable/rancher --name rancher --namespace cattle-system --version 2.2.8 --set tls=external --set privateCA=true --set addLocal=false --set auditLog.level=1 --description='RanchHand Deploy' --wait
  run_once: true
  when: "'rancher' not in charts.stdout"

