openapi: 3.0.1
info:
  title: ranchhand
  description: Deploy Rancher in HA mode onto existing hardware
  x-cortex-tag: ranchhand
  x-cortex-type: service
  x-cortex-git:
    github:
      alias: cortex
      repository: dominodatalab/ranchhand
  x-cortex-owners:
    - name: eng-distributions
      type: group
      provider: OKTA
      description: Distributions
  x-cortex-circle-ci:
    projects:
      - projectSlug: github/dominodatalab/ranchhand