---
docker_version:
  xenial: 5:18.09.8~3-0~ubuntu-xenial
  focal: 5:19.03.12~3-0~ubuntu-focal
  bionic: 5:18.09.9~3-0~ubuntu-bionic
  jammy: 5:24.0.9-1~ubuntu.22.04~jammy
docker_ce_yum_version: 18.09.6-3.el7
containerd_yum_version: 1.2.10-3.2.el7
container_selinux_yum_version: 2.107-3.el7
docker_ce_repo_root: https://mirrors.domino.tech/artifacts/docker
docker_daemon_json: |
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m",
    "max-file": "3"
  }
