---
- name: Fetch Helm Version
  command: helm version --server
  changed_when: false
  register: helm_version
  ignore_errors: yes
  run_once: true

- name: Create K8s Service Account
  command: kubectl -n kube-system create serviceaccount tiller
  when: helm_version is failed
  run_once: true

- name: Create Cluster Role Binding
  command: kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  when: helm_version is failed
  run_once: true

- name: helm Init tiller
  command: helm init --service-account tiller --wait --upgrade
  when: helm_version is failed
  run_once: true
