---
- import_tasks: secrets.yml
  run_once: true

- import_tasks: cert-manager.yml
  run_once: true

- import_tasks: rancher.yml
  run_once: true

- import_tasks: password.yml
  run_once: true
  when: rancher_password != ''
