---
- name: Probe Helm Repos
  command: helm repo list --output json
  changed_when: false
  run_once: true
  # Ignore errors since an empty repo list returns exit code = 1
  ignore_errors: true
  register: repos

- name: Probe Helm Charts
  command: helm list --all-namespaces --output json
  changed_when: false
  run_once: true
  register: charts

- name: Include secrets.yml
  include_tasks: secrets.yml
  run_once: true

- name: Include cert-manager.yml
  include_tasks: cert-manager.yml
  run_once: true

- name: Include rancher.yml
  include_tasks: rancher.yml
  run_once: true

