---
- name: Probe Helm Repos
  command: helm repo list --output json
  # Ignore errors since an empty repo list returns exit code = 1
  ignore_errors: true
  register: repos

- name: Probe Helm Charts
  command: helm list --all-namespaces --output json
  register: charts

- import_tasks: secrets.yml

- import_tasks: cert-manager.yml

- import_tasks: rancher.yml

- import_tasks: password.yml
  when: rancher_password != ''
