---
- name: Probe Helm Repos
  command: helm repo list --output json
  changed_when: false
  run_once: true
  # Ignore errors since an empty repo list returns exit code = 1
  ignore_errors: true
  register: repos

- name: Probe Helm Charts
  command: helm list --output json
  changed_when: false
  run_once: true
  register: charts

- import_tasks: secrets.yml
  run_once: true

- import_tasks: cert-manager.yml
  run_once: true

- import_tasks: rancher.yml
  run_once: true

- import_tasks: password.yml
  run_once: true
  when: rancher_password != ''
