---
- name: Check if Rancher Admin Password is set to Default
  uri:
    url: https://localhost/v3-public/localProviders/local?action=login
    method: POST
    body_format: json
    body:
      username: admin
      password: admin
    validate_certs: no
    return_content: yes
    status_code: [201, 401]
  register: login

- name: Update Rancher Admin Password
  uri:
    url: https://localhost/v3/users?action=changepassword
    method: POST
    headers:
      Authorization: "Bearer {{ login.json.token }}"
    body_format: json
    body:
      currentPassword: admin
      newPassword: "{{ rancher_password }}"
    validate_certs: no
    return_content: yes
  when: login.status_code == 201
