---
- name: Probe tls-ca Secret
  command: kubectl --namespace cattle-system get secrets tls-ca
  register: secret
  changed_when: false
  ignore_errors: true

- name: Create tls-ca Secret
  become: true
  command: "kubectl --kubeconfig=/home/{{ ansible_user_id }}/.kube/config --namespace cattle-system create secret generic tls-ca --from-file=cacerts.pem=/etc/ssl/private/dominodatalab.com.pem"
  when: secret is failed