---
# These Modules all Run Locally (local_action) to Generate TLS certs

- name: Generate an OpenSSL Private Key
  local_action:
    module: openssl_privatekey
    path: "{{ local_output_dir }}/dominodatalab.com.pem"

- name: Generate an OpenSSL Certificate Signing Request
  local_action:
    module: openssl_csr
    path: "{{ local_output_dir }}/dominodatalab.com.csr"
    privatekey_path: "{{ local_output_dir }}/dominodatalab.com.pem"
    common_name: "{{ cert_names.split(',')[0] | regex_replace('DNS:') }}"
    subject_alt_name: "{{ cert_names }}"
    organization_name: Domino Data Lab, Inc.
    organizational_unit_name: Platform Engineering
    key_usage: ["Digital Signature", "Certificate Sign"]
    key_usage_critical: yes
    extended_key_usage: ["TLS Web Server Authentication", "TLS Web Client Authentication"]
    basic_constraints: "CA:TRUE"
    basic_constraints_critical: yes

- name: Generate a Self Signed OpenSSL Certificate
  local_action:
    module: openssl_certificate
    path: "{{ local_output_dir }}/dominodatalab.com.crt"
    privatekey_path: "{{ local_output_dir }}/dominodatalab.com.pem"
    csr_path: "{{ local_output_dir }}/dominodatalab.com.csr"
    provider: selfsigned
