---
- name: Create Self Signed OpenSSL Certificate Directory
  become: true
  file: path="{{ item }}" state=directory
  with_items:
    - /etc/ssl/crt
    - /etc/ssl/private
    - /etc/ssl/csr

- name: Install Crypto Pkgs
  become: true
  apt:
    name:
      - python3-pip
      - libssl-dev

- name: Install Python Crypto Module
  become: true
  pip: name=pyOpenSSL

- name: Generate an OpenSSL Private Key (one host only)
  become: true
  openssl_privatekey:
    path: /etc/ssl/private/dominodatalab.com.pem
    mode: u+rw
    owner: "{{ ansible_user_id }}"
  
- name: Generate an OpenSSL Certificate Signing Request (one host only)
  become: true
  openssl_csr:
    path: /etc/ssl/csr/dominodatalab.com.csr
    privatekey_path: /etc/ssl/private/dominodatalab.com.pem
    common_name: "{{ cert_names.split(',')[0] | regex_replace('DNS:') }}"
    subject_alt_name: "{{ cert_names }}"
    organization_name: Domino Data Lab, Inc.
    organizational_unit_name: Platform Team RanchHand
  
- name: Generate a Self Signed OpenSSL Certificate (one host only)
  become: true
  openssl_certificate:
    path: /etc/ssl/crt/dominodatalab.com.crt
    privatekey_path: /etc/ssl/private/dominodatalab.com.pem
    csr_path: /etc/ssl/csr/dominodatalab.com.csr
    provider: selfsigned
  
- name: Download Self Signed OpenSSL Certificate for RKE Template
  become: true
  fetch:
      src: "/etc/ssl/{{ item }}"
      dest: "{{ local_output_dir }}/"
      flat: yes
  with_items:
    - crt/dominodatalab.com.crt
    - private/dominodatalab.com.pem
