---
- name: Probe Helm Repos
  command: helm repo list --output json
  changed_when: false
  run_once: true
  # Ignore errors since an empty repo list returns exit code = 1
  ignore_errors: true
  register: repos

- name: Probe Helm Charts
  command: helm list --all-namespaces --output json
  changed_when: false
  run_once: true
  register: charts

- import_tasks: newrelic.yml
  run_once: true
  when: newrelic.licensekey != ''
