---
- name: Add Docker Repository
  yum_repository:
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker & Dependencies
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - "docker-ce-{{ docker_ce_yum_version }}"
      - "docker-ce-cli-{{ docker_ce_yum_version }}"
      - containerd.io

- name: Enable and Start Docker
  systemd:
    state: started
    name: docker
    enabled: yes