---
- name: update apt update
  become: true
  apt: update_cache=yes cache_valid_time=86400 #One day
      
- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker Dependencies
  become: true
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker & Dependencies
  become: true
  apt:
    name:
      - containerd.io
      - "docker-ce={{ docker_ce_ubuntu_version }}"
    state: present

- name: Add user to docker
  become: true
  user:
    name: "{{ ansible_user_id }}"
    group: docker