# Master Playbook
# THE standard playbook for Domino Rancher Deployments

---
- hosts: all

  collections:
    - ansible.posix
    - community.crypto
    - community.general

  vars_prompt:
    - name: cert_names
      prompt: CA 'comma separated string' of values prefixed by their options. (i.e., email, URI, DNS, RID, IP, dirName, otherName and the ones specific to your CA)
      private: no

  pre_tasks:
    - name: Create local output directory
      local_action:
        module: file
        path: "{{ local_output_dir | default('/tmp') }}"
        state: directory

  roles:
    - name: proxy
      proxy_settings_http_proxy: http_proxy 
      proxy_settings_no_proxy:   no_proxy 
      proxy_settings_https_proxy: https_proxy
      when:
        # is_proxy defaults to false
        is_proxy | bool
    - name: system-checks
    - name: docker
    - name: rke
    - name: rancher
    - name: newrelic
