# Master Playbook
# THE standard playbook for Domino Rancher Deployments

---
- hosts: all

  pre_tasks:
    - name: update apt update
      become: true
      apt: update_cache=yes cache_valid_time=86400 #One day

  roles:
    - system-checks
    - docker
    - rke
    - helm
    - rancher

