---

helm:
  host: "{{ lookup('env', 'HELM_V3_REGISTRY_HOST') }}"
  user: "{{ lookup('env', 'HELM_V3_REGISTRY_USER') }}"
  password: "{{ lookup('env', 'HELM_V3_REGISTRY_PASSWORD') }}"
  namespace: "domino-eng-service-artifacts"
newrelic:
  licensekey: "{{ lookup('env', 'NEWRELIC_LICENSEKEY') }}"
  namespace: "monitoring"
  service_name: nri-bundle
  service_version: "1.11.3-0.1.0"
