# Master Playbook
# THE standard playbook for Domino Rancher Deployments

---
- hosts: all
  vars:
    adminPassword: ''  # Set on CLI: -e adminPassword=<xxx>
    recommendedCpus: 4
    recommendedMemory: 16
    recommendedNodes: 3
    tools_dir: "/home/ubuntu/ranchhand/tools"
  pre_tasks:

    - name: Create RanchHand Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ranchhand
        - "{{ tools_dir }}"

    - name: update apt update
      become: true
      apt: update_cache=yes cache_valid_time=86400 #One day

  roles:
    - system-checks
    - docker
    - rke
    - helm

  # TODO:
  # 1) modifyRancherAdminPassword

